import fs from 'node:fs/promises';
import path from 'node:path';

import {getAuthTables, type BetterAuthDBSchema, type DBFieldAttribute} from 'better-auth/db';
import type {BetterAuthOptions} from 'better-auth';
import {
  initGetFieldName,
  initGetModelName,
  type DBAdapter,
  type DBAdapterInstance,
  type DBAdapterSchemaCreation,
  type DBTransactionAdapter,
} from 'better-auth/adapters';

import type {SqlfuConfig, SqlfuProjectConfig} from './types.js';

const adapterId = 'sqlfu';
const adapterName = 'sqlfu Better Auth adapter';
const beginMarker = '-- sqlfu:better-auth begin';
const endMarker = '-- sqlfu:better-auth end';

type BetterAuthAdapterConfig = {usePlural?: boolean | undefined};

export interface SqlfuBetterAuthAdapterInput<Options extends BetterAuthOptions = BetterAuthOptions> {
  sqlfu: SqlfuConfig | SqlfuProjectConfig;
  adapter: DBAdapterInstance<Options>;
  projectRoot?: string;
}

export function sqlfuBetterAuthAdapter<Options extends BetterAuthOptions = BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
): DBAdapterInstance<Options> {
  return (options) => wrapAdapter(input, input.adapter(options));
}

function wrapAdapter<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  base: DBAdapter<Options>,
): DBAdapter<Options> {
  return {
    ...base,
    id: adapterId,
    options: {
      ...base.options,
      adapterConfig: {
        ...base.options?.adapterConfig,
        adapterId,
        adapterName,
      },
    },
    async transaction(callback) {
      return base.transaction(async (tx) => callback(wrapTransactionAdapter(input, tx)));
    },
    async createSchema(options, file) {
      return createSqlfuBetterAuthSchema(input, base, options, file);
    },
  };
}

function wrapTransactionAdapter<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  base: DBTransactionAdapter<Options>,
): DBTransactionAdapter<Options> {
  return {
    ...base,
    id: adapterId,
    options: {
      ...base.options,
      adapterConfig: {
        ...base.options?.adapterConfig,
        adapterId,
        adapterName,
      },
    },
    async createSchema(options, file) {
      return createSqlfuBetterAuthSchema(input, base, options, file);
    },
  };
}

async function createSqlfuBetterAuthSchema<Options extends BetterAuthOptions>(
  input: SqlfuBetterAuthAdapterInput<Options>,
  adapter: DBAdapter<Options> | DBTransactionAdapter<Options>,
  options: Options,
  file: string | undefined,
): Promise<DBAdapterSchemaCreation> {
  const projectRoot = resolveProjectRoot(input);
  const definitionsPath = path.resolve(projectRoot, input.sqlfu.definitions);
  const requestedPath = file ? path.resolve(projectRoot, file) : definitionsPath;

  if (requestedPath !== definitionsPath) {
    throw new Error(
      [
        `sqlfuBetterAuthAdapter can only generate ${path.relative(projectRoot, definitionsPath)}.`,
        `Received output file ${file || '<none>'}.`,
        'Run Better Auth generate with the configured sqlfu definitions file, or omit --output.',
      ].join('\n'),
    );
  }

  const currentDefinitionsSql = await readExistingDefinitions(definitionsPath);
  const generatedSection = renderBetterAuthManagedSection({
    tables: getAuthTables(options),
    options,
    adapterConfig: adapter.options?.adapterConfig,
  });
  const nextDefinitionsSql = replaceBetterAuthManagedSection(currentDefinitionsSql, generatedSection);

  return {
    code: nextDefinitionsSql === currentDefinitionsSql ? '' : nextDefinitionsSql,
    path: outputPathForBetterAuthCli(file, definitionsPath),
    overwrite: true,
  };
}

function resolveProjectRoot<Options extends BetterAuthOptions>(input: SqlfuBetterAuthAdapterInput<Options>) {
  if ('projectRoot' in input.sqlfu) return input.sqlfu.projectRoot;
  return input.projectRoot || process.cwd();
}

async function readExistingDefinitions(definitionsPath: string): Promise<string> {
  try {
    return await fs.readFile(definitionsPath, 'utf8');
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') {
      return '';
    }
    throw error;
  }
}

function outputPathForBetterAuthCli(file: string | undefined, definitionsPath: string) {
  if (file && !path.isAbsolute(file)) return file;
  return path.relative(process.cwd(), definitionsPath);
}

function renderBetterAuthManagedSection(input: {
  tables: BetterAuthDBSchema;
  options: BetterAuthOptions;
  adapterConfig: BetterAuthAdapterConfig | undefined;
}) {
  const sql = renderBetterAuthSchemaSql(input);
  return [
    beginMarker,
    '-- generated by Better Auth through sqlfuBetterAuthAdapter; edit Better Auth config instead',
    sql.trim(),
    endMarker,
  ]
    .filter(Boolean)
    .join('\n');
}

function replaceBetterAuthManagedSection(currentDefinitionsSql: string, generatedSection: string) {
  if (!currentDefinitionsSql.trim()) {
    return `${generatedSection}\n`;
  }

  const beginIndexes = markerIndexes(currentDefinitionsSql, beginMarker);
  const endIndexes = markerIndexes(currentDefinitionsSql, endMarker);

  if (beginIndexes.length === 0 && endIndexes.length === 0) {
    throw new Error(
      [
        'definitions.sql already contains application SQL but no sqlfu Better Auth managed section.',
        'Add the managed section markers before running Better Auth generate:',
        '',
        beginMarker,
        endMarker,
      ].join('\n'),
    );
  }
  if (beginIndexes.length !== 1 || endIndexes.length !== 1) {
    throw new Error('definitions.sql must contain exactly one sqlfu Better Auth managed section.');
  }
  const beginIndex = beginIndexes[0]!;
  const endIndex = endIndexes[0]!;
  if (endIndex < beginIndex) {
    throw new Error('definitions.sql has a malformed sqlfu Better Auth managed section.');
  }

  return [
    currentDefinitionsSql.slice(0, beginIndex),
    generatedSection,
    currentDefinitionsSql.slice(endIndex + endMarker.length),
  ].join('');
}

function markerIndexes(value: string, marker: string) {
  const indexes: number[] = [];
  let cursor = 0;
  while (cursor < value.length) {
    const index = value.indexOf(marker, cursor);
    if (index === -1) break;
    indexes.push(index);
    cursor = index + marker.length;
  }
  return indexes;
}

function renderBetterAuthSchemaSql(input: {
  tables: BetterAuthDBSchema;
  options: BetterAuthOptions;
  adapterConfig: BetterAuthAdapterConfig | undefined;
}) {
  const statements: string[] = [];
  const tables = Object.entries(input.tables).sort(compareTables);
  const useNumberId = usesNumericId(input.options);
  const getModelName = initGetModelName({
    schema: input.tables,
    usePlural: input.adapterConfig?.usePlural,
  });
  const getFieldName = initGetFieldName({
    schema: input.tables,
    usePlural: input.adapterConfig?.usePlural,
  });

  for (const [tableKey, table] of tables) {
    const tableName = getModelName(tableKey);
    const columns = [`${quoteIdentifier('id')} ${useNumberId ? 'integer' : 'text'} primary key not null`];
    const indexes: string[] = [];

    for (const [fieldKey, field] of Object.entries(table.fields)) {
      const fieldName = getFieldName({model: tableKey, field: fieldKey});
      if (fieldName === 'id') {
        throw new Error(`Better Auth table ${tableName} declares an id field; sqlfuBetterAuthAdapter owns id columns.`);
      }
      columns.push(renderColumn({field, fieldName, getFieldName, getModelName, useNumberId}));
      if (field.index) {
        indexes.push(renderIndex({tableName, fieldName, unique: field.unique === true}));
      }
    }

    statements.push(`create table ${quoteIdentifier(tableName)} (\n${columns.map((column) => `  ${column}`).join(',\n')}\n);`);
    statements.push(...indexes);
  }

  return statements.join('\n\n');
}

function compareTables(
  [leftKey, left]: [string, BetterAuthDBSchema[string]],
  [rightKey, right]: [string, BetterAuthDBSchema[string]],
) {
  const leftOrder = left.order === undefined ? Number.POSITIVE_INFINITY : left.order;
  const rightOrder = right.order === undefined ? Number.POSITIVE_INFINITY : right.order;
  if (leftOrder !== rightOrder) return leftOrder - rightOrder;
  return (left.modelName || leftKey).localeCompare(right.modelName || rightKey);
}

function usesNumericId(options: BetterAuthOptions) {
  const databaseOptions = options.advanced?.database as {generateId?: unknown; useNumberId?: unknown} | undefined;
  return databaseOptions?.generateId === 'serial' || databaseOptions?.useNumberId === true;
}

function renderColumn(input: {
  field: DBFieldAttribute;
  fieldName: string;
  getFieldName: ReturnType<typeof initGetFieldName>;
  getModelName: ReturnType<typeof initGetModelName>;
  useNumberId: boolean;
}) {
  const parts = [quoteIdentifier(input.fieldName), sqliteTypeFor(input.field, input.fieldName, input.useNumberId)];
  if (input.field.required !== false) parts.push('not null');
  if (input.field.unique) parts.push('unique');
  if (input.field.references) {
    parts.push(
      renderReference({
        field: input.field,
        getFieldName: input.getFieldName,
        getModelName: input.getModelName,
      }),
    );
  }
  return parts.join(' ');
}

function sqliteTypeFor(field: DBFieldAttribute, fieldName: string, useNumberId: boolean) {
  if (fieldName === 'id' || field.references?.field === 'id') return useNumberId ? 'integer' : 'text';
  if (Array.isArray(field.type)) return 'text';

  switch (field.type) {
    case 'string':
    case 'json':
    case 'string[]':
    case 'number[]':
      return 'text';
    case 'boolean':
    case 'number':
      return field.bigint ? 'bigint' : 'integer';
    case 'date':
      return 'date';
  }

  throw new Error(`Unsupported Better Auth field type ${JSON.stringify(field.type)} for field ${fieldName}.`);
}

function renderReference(input: {
  field: DBFieldAttribute;
  getFieldName: ReturnType<typeof initGetFieldName>;
  getModelName: ReturnType<typeof initGetModelName>;
}) {
  const reference = input.field.references!;
  const tableName = input.getModelName(reference.model);
  const fieldName = input.getFieldName({model: reference.model, field: reference.field});
  return `references ${quoteIdentifier(tableName)} (${quoteIdentifier(fieldName)}) on delete ${reference.onDelete || 'cascade'}`;
}

function renderIndex(input: {tableName: string; fieldName: string; unique: boolean}) {
  const indexName = `${input.tableName}_${input.fieldName}_${input.unique ? 'uidx' : 'idx'}`;
  return `create ${input.unique ? 'unique ' : ''}index ${quoteIdentifier(indexName)} on ${quoteIdentifier(input.tableName)} (${quoteIdentifier(input.fieldName)});`;
}

function quoteIdentifier(value: string) {
  return `"${value.replaceAll('"', '""')}"`;
}
