// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type SqlfuMigrationsRow = {
	name: string;
	checksum: string;
	applied_at: string;
};
