// Generated by `sqlfu generate`. Do not edit.

export * from "./find-post-by-slug.sql.ts";
export * from "./list-post-cards.sql.ts";

export const sqlfuQuerySources = [
	{ sqlFile: "find-post-by-slug.sql", generatedFile: "find-post-by-slug.sql.ts", sourceSql: "select id, slug, title, published\nfrom posts\nwhere slug = :slug\nlimit 1;\n" },
	{ sqlFile: "list-post-cards.sql", generatedFile: "list-post-cards.sql.ts", sourceSql: "select id, slug, title, published\nfrom post_cards\norder by id;\n" },
];
