// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type PostCardsRow = {
	id: number;
	slug: string;
	title: string;
	published: number;
};

export type PostsRow = {
	id: number;
	slug: string;
	title: string;
	body: string;
	published: number;
};
