import dedent from 'dedent';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {fileURLToPath} from 'node:url';
import {Project, ts} from 'ts-morph';

import {createNodeSqliteClient} from '../../src/index.js';
import {generateQueryTypes} from '../../src/typegen/index.js';
import {createTempFixtureRoot, withTrailingNewline, writeFixtureFiles} from '../fs-fixture.js';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

export type FixtureFile = {
  path: string;
  lang: string;
  content: string;
};

export type FixtureCase = {
  name: string;
  inputFiles: FixtureFile[];
  outputFiles: FixtureFile[];
  /**
   * Glob list from the output `<details data-outputs="…">` attribute. When present, this is
   * the sole source of truth for which generated files get asserted on (and regenerated by
   * `-u`): every matching file that `generate` actually wrote becomes a fence, every fence
   * whose path doesn't match gets dropped. Undefined means "respect whatever fences the
   * author already wrote" — the status quo for existing fixtures.
   */
  outputGlobs?: string[];
  expectedError?: string;
};

export type FixtureRunResult =
  | {
      kind: 'ok';
      outputs: Record<string, string>;
      /**
       * Formatted TypeScript diagnostics for the generated files — empty means the fixture's
       * emitted code typechecks cleanly against sqlfu's source. Empty-by-default so most
       * fixtures can just `.toEqual([])` without further ceremony.
       */
      diagnostics: string[];
    }
  | {kind: 'error'; message: string};

export function listFixtureFiles(root: string): string[] {
  return fs
    .globSync('*.md', {cwd: root})
    .map((name) => path.join(root, name))
    .sort();
}

export async function runFixtureCase(fixtureCase: FixtureCase): Promise<FixtureRunResult> {
  const root = await createTempFixtureRoot('generate-fixture');
  try {
    const files: Record<string, string> = {};
    for (const file of fixtureCase.inputFiles) {
      files[file.path] = file.content;
    }
    await writeFixtureFiles(root, files);

    const definitionsSql = files['definitions.sql'];
    if (definitionsSql) {
      await applyDefinitionsToDatabase(path.join(root, 'app.db'), definitionsSql);
    }

    try {
      await inWorkingDirectory(root, () => generateQueryTypes());
    } catch (error) {
      return {kind: 'error', message: String(error)};
    }

    const outputs: Record<string, string> = {};

    // `data-outputs` globs are the authoritative fence list — discover everything under the
    // fixture root and filter by the globs so `-u` can both refresh existing fences and add
    // new ones matching the declared pattern.
    if (fixtureCase.outputGlobs?.length) {
      const inputPaths = new Set(Object.keys(files));
      for (const relative of await discoverGeneratedFiles(root, inputPaths)) {
        if (matchesAnyGlob(relative, fixtureCase.outputGlobs)) {
          outputs[relative] = await fsp.readFile(path.join(root, relative), 'utf8');
        }
      }
    }

    // Pull in any hand-declared fence path that the globs didn't already cover. Missing files
    // surface as `<MISSING>` so regressions that drop an expected output fail loudly.
    for (const file of fixtureCase.outputFiles) {
      if (outputs[file.path] !== undefined) continue;
      try {
        outputs[file.path] = await fsp.readFile(path.join(root, file.path), 'utf8');
      } catch {
        outputs[file.path] = '<MISSING>';
      }
    }

    const diagnostics = await typecheckGeneratedFiles(root);

    return {kind: 'ok', outputs, diagnostics};
  } finally {
    await fsp.rm(root, {recursive: true, force: true});
  }
}

/**
 * Run TypeScript over the fixture's generated files (`sql/.generated/*.ts`), resolving
 * `'sqlfu'` and validator-library imports to the workspace copies that the real consumer
 * would hit. Diagnostics are filtered to errors that actually reference a `/sql/` path so
 * transient build noise from the workspace source tree doesn't sneak in.
 *
 * The sqlfu source tree is pre-loaded into a module-scoped `Project` on first call and
 * reused thereafter — parsing it per fixture was the dominant cost and made the suite
 * several-times slower. Per-fixture generated files are added on entry, removed on exit,
 * so fixtures don't cross-contaminate.
 */
async function typecheckGeneratedFiles(root: string): Promise<string[]> {
  const project = await ensureTypecheckProject();
  const generatedGlob = path.join(root, 'sql', '.generated', '**', '*.ts').split(path.sep).join('/');
  const addedFiles = project.addSourceFilesAtPaths(generatedGlob);
  try {
    const fixtureScope = path.sep === '/' ? `${root}/sql/` : `${root}${path.sep}sql${path.sep}`;
    return project
      .getPreEmitDiagnostics()
      .map((diagnostic) => project.formatDiagnosticsWithColorAndContext([diagnostic]))
      .filter((message) => message.includes(fixtureScope));
  } finally {
    for (const sourceFile of addedFiles) {
      project.removeSourceFile(sourceFile);
    }
  }
}

let sharedTypecheckProject: Project | undefined;
async function ensureTypecheckProject(): Promise<Project> {
  if (sharedTypecheckProject) return sharedTypecheckProject;
  const project = new Project({
    compilerOptions: {
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      target: ts.ScriptTarget.ESNext,
      lib: ['lib.esnext.d.ts'],
      strict: true,
      skipLibCheck: true,
      noEmit: true,
      // The `importExtension: '.ts'` config + the tsconfig-detected ts-import mode both emit
      // bare `.ts` specifiers in the generated barrel. A real consumer enables this in their
      // own tsconfig; we need the same here so those fixtures don't error out.
      allowImportingTsExtensions: true,
      paths: {
        sqlfu: [path.join(packageRoot, 'src', 'index.ts')],
        'better-sqlite3': [path.join(packageRoot, 'node_modules', 'better-sqlite3')],
        zod: [path.join(packageRoot, 'node_modules', 'zod')],
        'zod/mini': [path.join(packageRoot, 'node_modules', 'zod', 'mini')],
        valibot: [path.join(packageRoot, 'node_modules', 'valibot')],
        arktype: [path.join(packageRoot, 'node_modules', 'arktype')],
      },
      types: ['node'],
    },
  });
  project.addSourceFilesAtPaths(path.join(packageRoot, 'src', '**', '*.ts'));
  for (const sourceFile of project.getSourceFiles()) {
    if (sourceFile.getFilePath().includes(`${path.sep}src${path.sep}vendor${path.sep}`)) {
      project.removeSourceFile(sourceFile);
    }
  }
  sharedTypecheckProject = project;
  return project;
}

async function discoverGeneratedFiles(root: string, inputPaths: ReadonlySet<string>): Promise<string[]> {
  const discovered: string[] = [];
  async function walk(relative: string): Promise<void> {
    const entries = await fsp.readdir(path.join(root, relative), {withFileTypes: true});
    for (const entry of entries) {
      const entryRelative = relative ? `${relative}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        await walk(entryRelative);
        continue;
      }
      if (inputPaths.has(entryRelative)) continue;
      // The sqlite scaffolding the helper seeds from `definitions.sql` (plus the typegen
      // working copy under `.sqlfu/`) isn't a generator output — don't surface it as a fence.
      if (/\.(db|sqlite|sqlite3)(-journal|-wal|-shm)?$/.test(entry.name)) continue;
      discovered.push(entryRelative);
    }
  }
  await walk('');
  return discovered.sort();
}

function matchesAnyGlob(filePath: string, globs: string[]): boolean {
  return globs.some((glob) => path.matchesGlob(filePath, glob));
}

/**
 * A fixture file looks like:
 *
 *     intro paragraph...
 *
 *     <details>
 *     <summary>default config</summary>
 *
 *     ```ts (sqlfu.config.ts)
 *     ...
 *     ```
 *
 *     </details>
 *
 *     ## test name
 *
 *     <details>
 *     <summary>input</summary>
 *     ...
 *     </details>
 *
 *     <details>
 *     <summary>output</summary>
 *     ...
 *     </details>
 *
 * Each `##` heading is one test; its input/output (and optional error) live in nested
 * `<details>` blocks. The optional `default config` block at the top of the file supplies a
 * `sqlfu.config.ts` used by any test that doesn't declare its own.
 */
export function parseGenerateFixture(contents: string): FixtureCase[] {
  const cases: FixtureCase[] = [];
  const {defaultConfig, testArea} = extractDefaultConfig(contents);

  const headingPattern = /^##\s+(?<name>.+)$/gm;
  const headings = [...testArea.matchAll(headingPattern)];

  for (let i = 0; i < headings.length; i++) {
    const heading = headings[i];
    const next = headings[i + 1];
    const start = heading.index! + heading[0].length;
    const end = next ? next.index! : testArea.length;
    const body = testArea.slice(start, end);
    const name = heading.groups!.name.trim();

    const inputSection = extractDetailsSection(body, 'input');
    const inputFiles = parseFileBlocks(inputSection?.body || '');
    const outputSection = extractDetailsSection(body, 'output');
    const outputFiles = parseFileBlocks(outputSection?.body || '');
    // `data-outputs` lives on the input `<details>` so that scaffolding a new test only needs
    // one block — the output block is then auto-created by `-u`. The legacy position (on the
    // output tag) is still accepted for fixtures that already use it.
    const outputGlobs = parseOutputGlobs(
      inputSection?.attrs['data-outputs'] || outputSection?.attrs['data-outputs'],
    );
    const expectedError = extractDetailsBody(body, 'error')?.trim() || undefined;

    if (defaultConfig && !inputFiles.some((file) => file.path === 'sqlfu.config.ts')) {
      inputFiles.unshift(defaultConfig);
    }

    if (inputFiles.length === 0) {
      throw new Error(`Fixture "${name}" has no input files`);
    }

    cases.push({name, inputFiles, outputFiles, outputGlobs, expectedError});
  }

  return cases;
}

function parseOutputGlobs(raw: string | undefined): string[] | undefined {
  if (!raw) return undefined;
  const globs = raw.split(',').map((glob) => glob.trim()).filter(Boolean);
  return globs.length > 0 ? globs : undefined;
}

function extractDefaultConfig(contents: string): {defaultConfig?: FixtureFile; testArea: string} {
  const firstHeading = contents.search(/^##\s+/m);
  const headArea = firstHeading >= 0 ? contents.slice(0, firstHeading) : contents;
  const testArea = firstHeading >= 0 ? contents.slice(firstHeading) : '';

  const body = extractDetailsBody(headArea, 'default config');
  if (!body) {
    return {testArea};
  }

  const files = parseFileBlocks(body);
  const configFile = files.find((file) => file.path === 'sqlfu.config.ts');
  if (!configFile) {
    throw new Error(`"default config" block must contain a sqlfu.config.ts fence`);
  }
  return {defaultConfig: configFile, testArea};
}

function extractDetailsBody(container: string, summary: string): string | undefined {
  return extractDetailsSection(container, summary)?.body;
}

/**
 * Pull out a `<details><summary>{summary}</summary>…</details>` section along with the
 * attributes on the opening `<details>` tag. The attribute parse is intentionally simple:
 * `name="value"` pairs, no quote-less values, no escape sequences — enough for the
 * `data-outputs="glob,glob"` use case we actually want.
 */
function extractDetailsSection(
  container: string,
  summary: string,
): {body: string; attrs: Record<string, string>} | undefined {
  const escaped = summary.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(
    `<details([^>]*)>\\s*<summary>${escaped}</summary>([\\s\\S]*?)</details>`,
    'i',
  );
  const match = container.match(pattern);
  if (!match) return undefined;
  return {body: match[2], attrs: parseHtmlAttributes(match[1])};
}

function parseHtmlAttributes(tag: string): Record<string, string> {
  const attrs: Record<string, string> = {};
  for (const match of tag.matchAll(/([\w-]+)\s*=\s*"([^"]*)"/g)) {
    attrs[match[1]] = match[2];
  }
  return attrs;
}

function parseFileBlocks(section: string): FixtureFile[] {
  const files: FixtureFile[] = [];
  const fencePattern = /^```(?<lang>[\w-]+)\s*\((?<path>[^)]+)\)\s*\n(?<content>[\s\S]*?)^```\s*$/gm;

  for (const match of section.matchAll(fencePattern)) {
    const {lang, path: filePath, content} = match.groups!;
    files.push({
      path: filePath.trim(),
      lang,
      content,
    });
  }

  return files;
}

async function inWorkingDirectory<TResult>(cwd: string, fn: () => Promise<TResult>): Promise<TResult> {
  const previousCwd = process.cwd();
  process.chdir(cwd);
  try {
    return await fn();
  } finally {
    process.chdir(previousCwd);
  }
}

async function applyDefinitionsToDatabase(dbPath: string, definitionsSql: string) {
  const database = new DatabaseSync(dbPath);
  const client = createNodeSqliteClient(database);
  try {
    await client.raw(withTrailingNewline(dedent(definitionsSql)));
  } finally {
    database.close();
  }
}

/**
 * Rewrite the `output` block of the named test in `fixturePath`.
 *
 *   - If `outputGlobs` is provided, the block is regenerated from scratch: the fence list is
 *     exactly the paths in `outputs` (typically already filtered to match the globs), sorted
 *     alphabetically. Any previously hand-written fence that doesn't match the globs gets
 *     dropped. This is the "curated by globs" mode — deterministic, same output every run.
 *   - Otherwise, each existing `(path)`-tagged fence gets its body refreshed from `outputs`;
 *     fences whose paths aren't in `outputs` are left alone. This is the legacy mode for
 *     pre-globs fixtures that hand-curate their fence list.
 */
export function updateFixtureOutputs(
  fixturePath: string,
  testName: string,
  outputs: Record<string, string>,
  input: {outputGlobs?: string[]} = {},
): void {
  const contents = fs.readFileSync(fixturePath, 'utf8');
  const updated = rewriteTestOutputs(contents, testName, outputs, input.outputGlobs);
  if (updated !== contents) {
    fs.writeFileSync(fixturePath, updated);
  }
}

function rewriteTestOutputs(
  contents: string,
  testName: string,
  outputs: Record<string, string>,
  outputGlobs: string[] | undefined,
): string {
  const headings = [...contents.matchAll(/^##[ \t]+(.+?)[ \t]*$/gm)];
  const target = headings.findIndex((heading) => heading[1].trim() === testName);
  if (target < 0) {
    throw new Error(`Test section "${testName}" not found in fixture`);
  }

  const sectionStart = headings[target].index!;
  const sectionEnd = headings[target + 1]?.index ?? contents.length;
  const rewrittenSection = rewriteOutputBlock(
    contents.slice(sectionStart, sectionEnd),
    outputs,
    outputGlobs,
  );

  return contents.slice(0, sectionStart) + rewrittenSection + contents.slice(sectionEnd);
}

function rewriteOutputBlock(
  section: string,
  outputs: Record<string, string>,
  outputGlobs: string[] | undefined,
): string {
  const outputPattern = /(<details[^>]*>\s*<summary>output<\/summary>)([\s\S]*?)(<\/details>)/;
  if (outputPattern.test(section)) {
    return section.replace(outputPattern, (_match, open: string, inner: string, close: string) => {
      if (outputGlobs) {
        return `${open}${renderFenceBlock(outputs)}${close}`;
      }
      return `${open}${refreshExistingFences(inner, outputs)}${close}`;
    });
  }

  // No output block yet — if the input block declared `data-outputs`, scaffold one in-place
  // right after the input block. This is the "write only the input, get the rest for free"
  // path that keeps new fixtures a single `<details>` to author.
  if (!outputGlobs) return section;
  return section.replace(
    /(<details[^>]*>\s*<summary>input<\/summary>[\s\S]*?<\/details>)/,
    (match, inputBlock: string) => {
      return `${inputBlock}\n\n<details>\n<summary>output</summary>${renderFenceBlock(outputs)}</details>`;
    },
  );
}

function refreshExistingFences(inner: string, outputs: Record<string, string>): string {
  return inner.replace(
    /(^```[\w-]+[ \t]*\(([^)]+)\)[ \t]*\n)([\s\S]*?)(^```[ \t]*$)/gm,
    (match, openFence: string, rawPath: string, _oldContent: string, closeFence: string) => {
      const filePath = rawPath.trim();
      const actual = outputs[filePath];
      if (actual === undefined) return match;
      return `${openFence}${actual}${closeFence}`;
    },
  );
}

/**
 * Produce the body of the `<details>…</details>` from scratch: one fence per path, sorted.
 * Surrounding blank lines match the style of hand-written fixtures.
 */
function renderFenceBlock(outputs: Record<string, string>): string {
  const paths = Object.keys(outputs).sort();
  if (paths.length === 0) return '\n\n';

  const blocks = paths.map((filePath) => {
    const lang = inferFenceLanguage(filePath);
    const body = outputs[filePath];
    const trailing = body.endsWith('\n') ? '' : '\n';
    return `\`\`\`${lang} (${filePath})\n${body}${trailing}\`\`\``;
  });
  return `\n\n${blocks.join('\n\n')}\n\n`;
}

function inferFenceLanguage(filePath: string): string {
  const extension = filePath.slice(filePath.lastIndexOf('.') + 1);
  if (extension === 'ts' || extension === 'tsx') return 'ts';
  if (extension === 'js' || extension === 'mjs' || extension === 'cjs') return 'js';
  if (extension === 'json') return 'json';
  if (extension === 'sql') return 'sql';
  if (extension === 'md') return 'md';
  return extension || 'txt';
}
