import dedent from 'dedent';
import * as esbuild from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {pathToFileURL} from 'node:url';
import {expect, test} from 'vitest';

import {createNodeSqliteClient} from '../../src/index.js';
import {migrationsFromBundle, type MigrationBundle} from '../../src/migrations/index.js';
import type {Client} from '../../src/types.js';
import {generateQueryTypes} from '../../src/typegen/index.js';
import {createTempFixtureRoot, writeFixtureFiles, dumpFixtureFs} from '../fs-fixture.js';

const packageRoot = path.resolve(path.dirname(import.meta.filename), '../..');

test('generate emits a typed migrations bundle that can apply migrations without reading the filesystem', async () => {
  await using project = await createBundleFixture({
    'definitions.sql': `create table posts (id integer primary key, slug text not null);`,
    'migrations/2026-04-10T00.00.00.000Z_create_posts.sql': dedent`
      create table posts (id integer primary key, slug text not null);
    `,
    'migrations/2026-04-10T01.00.00.000Z_add_body.sql': dedent`
      alter table posts add column body text;
    `,
  });

  await project.generate();

  expect(await project.dumpGeneratedMigrations()).toMatchInlineSnapshot(`
    "migrations/
      .generated/
        migrations.ts
          // Generated by \`sqlfu generate\`. Do not edit.
          // A bundle of every migration in migrations/,
          // importable from runtimes without filesystem access (durable objects, edge workers, browsers).
          // Use \`migrate(client)\` for the common path, or \`migrations\` for lower-level control.

          import {applyMigrations, migrationsFromBundle, type AsyncClient, type Client, type SyncClient} from 'sqlfu';

          export const migrations = {
            "migrations/2026-04-10T00.00.00.000Z_create_posts.sql": "create table posts (id integer primary key, slug text not null);\\n",
            "migrations/2026-04-10T01.00.00.000Z_add_body.sql": "alter table posts add column body text;\\n",
          };

          export function migrate(client: SyncClient): void;
          export function migrate(client: AsyncClient): Promise<void>;
          export function migrate(client: Client): void | Promise<void> {
            return applyMigrations(client, {
              migrations: migrationsFromBundle(migrations),
              preset: "sqlfu",
            });
          }

          export type MigrationBundle = typeof migrations;
    "
  `);

  const {migrations, migrate} = await project.importBundle();
  const database = new DatabaseSync(':memory:');
  const client = createNodeSqliteClient(database);
  try {
    expect(Object.keys(migrations)).toEqual([
      'migrations/2026-04-10T00.00.00.000Z_create_posts.sql',
      'migrations/2026-04-10T01.00.00.000Z_add_body.sql',
    ]);

    migrate(client);

    const columns = await client.all<{name: string}>({
      sql: `select name from pragma_table_info('posts') order by cid`,
      args: [],
    });
    expect(columns).toMatchObject([{name: 'id'}, {name: 'slug'}, {name: 'body'}]);

    const applied = await client.all<{name: string}>({
      sql: `select name from sqlfu_migrations order by name`,
      args: [],
    });
    expect(applied).toMatchObject([
      {name: '2026-04-10T00.00.00.000Z_create_posts'},
      {name: '2026-04-10T01.00.00.000Z_add_body'},
    ]);
  } finally {
    database.close();
  }
});

test('generate emits an empty bundle when there are no migration files yet', async () => {
  await using project = await createBundleFixture({
    'definitions.sql': `create table posts (id integer primary key);`,
  });

  await project.generate();

  const {migrations} = await project.importBundle();
  expect(migrations).toEqual({});
  expect(migrationsFromBundle(migrations)).toEqual([]);
});

test('generated migrate uses the configured migration preset', async () => {
  await using project = await createBundleFixture(
    {
      'definitions.sql': `create table posts (id integer primary key);`,
      'migrations/0000_create_posts.sql': `create table posts (id integer primary key);`,
    },
    {migrationsConfig: `{ path: './migrations', preset: 'd1' }`},
  );

  await project.generate();

  const {migrate} = await project.importBundle();
  const database = new DatabaseSync(':memory:');
  const client = createNodeSqliteClient(database);
  try {
    migrate(client);

    const applied = client.all<{name: string}>({
      sql: `select name from d1_migrations order by name`,
      args: [],
    });
    expect(applied).toMatchObject([{name: '0000_create_posts.sql'}]);
  } finally {
    database.close();
  }
});

async function createBundleFixture(
  files: Record<string, string>,
  options: {migrationsConfig: string} = {migrationsConfig: `'./migrations'`},
) {
  const root = await createTempFixtureRoot('bundle');
  await writeFixtureFiles(root, {
    'sqlfu.config.ts': dedent`
      export default {
        db: './app.db',
        migrations: ${options.migrationsConfig},
        definitions: './definitions.sql',
        queries: './sql',
      };
    `,
    ...files,
  });

  // typegen needs a real dev db to extract the schema from.
  const appDbPath = path.join(root, 'app.db');
  const database = new DatabaseSync(appDbPath);
  try {
    const definitions = files['definitions.sql'];
    if (definitions?.trim()) {
      database.exec(definitions);
    }
  } finally {
    database.close();
  }

  return {
    root,
    async generate() {
      const previousCwd = process.cwd();
      process.chdir(root);
      try {
        await generateQueryTypes();
      } finally {
        process.chdir(previousCwd);
      }
    },
    async dumpGeneratedMigrations() {
      return dumpFixtureFs(root, {includeGlobs: ['migrations/.generated/**/*.ts']});
    },
    async importBundle(): Promise<{
      migrations: MigrationBundle;
      migrate(client: Client): void | Promise<void>;
    }> {
      const sourcePath = path.join(root, 'migrations', '.generated', 'migrations.ts');
      const outputPath = sourcePath.replace(/\.ts$/, '.mjs');
      await esbuild.build({
        entryPoints: [sourcePath],
        outfile: outputPath,
        bundle: true,
        format: 'esm',
        platform: 'neutral',
        target: 'es2022',
        absWorkingDir: packageRoot,
        alias: {sqlfu: './src/index.ts'},
        nodePaths: [path.join(packageRoot, 'node_modules')],
      });
      return import(pathToFileURL(outputPath).href);
    },
    async [Symbol.asyncDispose]() {
      await fs.rm(root, {recursive: true, force: true});
    },
  };
}
