import dedent from 'dedent';
import fs from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {pathToFileURL} from 'node:url';
import {ts} from 'ts-morph';
import {expect, test} from 'vitest';

import {createNodeSqliteClient} from '../../src/client.js';
import {createNodeHost} from '../../src/core/node-host.js';
import {applyMigrations, migrationsFromBundle, type MigrationBundle} from '../../src/migrations/index.js';
import {generateQueryTypes} from '../../src/typegen/index.js';
import {createTempFixtureRoot, writeFixtureFiles, dumpFixtureFs} from '../fs-fixture.js';

test('generate emits a typed migrations bundle that can apply migrations without reading the filesystem', async () => {
  await using project = await createBundleFixture({
    'definitions.sql': `create table posts (id integer primary key, slug text not null);`,
    'migrations/2026-04-10T00.00.00.000Z_create_posts.sql': dedent`
      create table posts (id integer primary key, slug text not null);
    `,
    'migrations/2026-04-10T01.00.00.000Z_add_body.sql': dedent`
      alter table posts add column body text;
    `,
  });

  await project.generate();

  expect(await project.dumpGeneratedMigrations()).toMatchInlineSnapshot(`
    "migrations/
      .generated/
        migrations.ts
          // Generated by \`sqlfu generate\`. Do not edit.
          // A bundle of every migration in migrations/,
          // importable from runtimes without filesystem access (durable objects, edge workers, browsers).
          // Pair with \`migrationsFromBundle\` + \`applyMigrations\` from 'sqlfu'.
          
          const bundle = {
            "migrations/2026-04-10T00.00.00.000Z_create_posts.sql": "create table posts (id integer primary key, slug text not null);\\n",
            "migrations/2026-04-10T01.00.00.000Z_add_body.sql": "alter table posts add column body text;\\n",
          };
          
          export default bundle;
          
          export type MigrationBundle = typeof bundle;
    "
  `);

  const {default: bundle} = await project.importBundle();
  const host = await createNodeHost();
  const database = new DatabaseSync(':memory:');
  const client = createNodeSqliteClient(database);
  try {
    await applyMigrations(host, client, {migrations: migrationsFromBundle(bundle)});

    const columns = await client.all<{name: string}>({
      sql: `select name from pragma_table_info('posts') order by cid`,
      args: [],
    });
    expect(columns).toMatchObject([
      {name: 'id'},
      {name: 'slug'},
      {name: 'body'},
    ]);

    const applied = await client.all<{name: string}>({
      sql: `select name from sqlfu_migrations order by name`,
      args: [],
    });
    expect(applied).toMatchObject([
      {name: '2026-04-10T00.00.00.000Z_create_posts'},
      {name: '2026-04-10T01.00.00.000Z_add_body'},
    ]);
  } finally {
    database.close();
  }
});

test('generate emits an empty bundle when there are no migration files yet', async () => {
  await using project = await createBundleFixture({
    'definitions.sql': `create table posts (id integer primary key);`,
  });

  await project.generate();

  const {default: bundle} = await project.importBundle();
  expect(bundle).toEqual({});
  expect(migrationsFromBundle(bundle)).toEqual([]);
});

async function createBundleFixture(files: Record<string, string>) {
  const root = await createTempFixtureRoot('bundle');
  await writeFixtureFiles(root, {
    'sqlfu.config.ts': dedent`
      export default {
        db: './app.db',
        migrations: './migrations',
        definitions: './definitions.sql',
        queries: './sql',
      };
    `,
    ...files,
  });

  // typegen needs a real dev db to extract the schema from.
  const appDbPath = path.join(root, 'app.db');
  const database = new DatabaseSync(appDbPath);
  try {
    const definitions = files['definitions.sql'];
    if (definitions?.trim()) {
      database.exec(definitions);
    }
  } finally {
    database.close();
  }

  return {
    root,
    async generate() {
      const previousCwd = process.cwd();
      process.chdir(root);
      try {
        await generateQueryTypes();
      } finally {
        process.chdir(previousCwd);
      }
    },
    async dumpGeneratedMigrations() {
      return dumpFixtureFs(root, {includeGlobs: ['migrations/.generated/**/*.ts']});
    },
    async importBundle(): Promise<{default: MigrationBundle}> {
      const sourcePath = path.join(root, 'migrations', '.generated', 'migrations.ts');
      const source = await fs.readFile(sourcePath, 'utf8');
      const outputPath = sourcePath.replace(/\.ts$/, '.mjs');
      const transpiled = ts.transpileModule(source, {
        compilerOptions: {
          module: ts.ModuleKind.ESNext,
          target: ts.ScriptTarget.ESNext,
        },
      });
      await fs.writeFile(outputPath, transpiled.outputText);
      return import(pathToFileURL(outputPath).href);
    },
    async [Symbol.asyncDispose]() {
      await fs.rm(root, {recursive: true, force: true});
    },
  };
}
