import fs from 'node:fs/promises';
import path from 'node:path';

import dedent from 'dedent';
import {execaCommand} from 'execa';
import {expect, test} from 'vitest';

import {sqlfuBetterAuthAdapter} from '../src/better-auth.js';
import {extractSchema} from '../src/sqlite-text.js';
import {createTempFixtureRoot, writeFixtureFiles} from './fs-fixture.js';
import {createMigrationsFixture} from './migrations/fixture.js';

const packageRoot = path.resolve(path.dirname(import.meta.filename), '..');

declare const fixtureBetterAuth: any;
declare const fixtureCreateBaseAdapter: any;
declare const fixtureSqlfuBetterAuthAdapter: any;
declare const fixtureSqlfuConfig: any;

test('sqlfuBetterAuthAdapter preserves runtime methods and wraps createSchema', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });

  const create = async () => ({id: 'created-user'});
  const baseAdapter = createBaseAdapter({create});
  const adapter = sqlfuBetterAuthAdapter({
    sqlfu: {definitions: './definitions.sql', queries: './sql'},
    projectRoot: fixture.root,
    adapter: () => baseAdapter,
  })({});

  expect(adapter).toMatchObject({
    id: 'sqlfu',
    create,
    options: {
      adapterConfig: {
        adapterId: 'sqlfu',
        adapterName: 'sqlfu Better Auth adapter',
      },
    },
  });
  const transactionAdapter = await adapter.transaction(async (tx) => tx);

  const schema = await adapter.createSchema?.({}, 'definitions.sql');

  expect(schema).toMatchObject({
    path: 'definitions.sql',
    overwrite: true,
  });
  expect(schema?.code).toContain('-- sqlfu:better-auth begin');
  expect(schema?.code).toContain('create table "user"');
  expect(schema?.code).toContain('"email" text not null unique');
  expect(schema?.code).toContain('-- sqlfu:better-auth end');
  expect(transactionAdapter).toMatchObject({
    id: 'sqlfu',
    options: {
      adapterConfig: {
        adapterId: 'sqlfu',
        adapterName: 'sqlfu Better Auth adapter',
      },
    },
  });
});

test('createSchema preserves application SQL outside the managed Better Auth section', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': dedent`
        create table "posts" (
          "id" integer primary key not null,
          "slug" text not null unique
        );

        -- sqlfu:better-auth begin
        create table "obsolete_auth_table" ("id" text primary key not null);
        -- sqlfu:better-auth end

        create table "comments" (
          "id" integer primary key not null,
          "postId" integer not null references "posts" ("id") on delete cascade
        );
      `,
    },
  });

  const schema = await createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql');

  expect(schema?.code).toMatch(/^create table "posts"/);
  expect(schema?.code).toContain('create table "comments"');
  expect(schema?.code).toContain('create table "user"');
  expect(schema?.code).not.toContain('obsolete_auth_table');
  expect(schema?.code).toMatch(
    /-- sqlfu:better-auth begin\n-- generated by Better Auth through sqlfuBetterAuthAdapter; edit Better Auth config instead\ncreate table "user"/,
  );
});

test('createSchema returns empty code when definitions are already up to date', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });
  const adapter = createAdapterForFixture(fixture);
  const firstSchema = await adapter.createSchema?.({}, 'definitions.sql');
  await fixture.writeText('definitions.sql', firstSchema!.code);

  const secondSchema = await adapter.createSchema?.({}, 'definitions.sql');

  expect(secondSchema).toMatchObject({
    code: '',
    path: 'definitions.sql',
    overwrite: true,
  });
});

test('createSchema rejects an output file that is not the configured definitions file', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });

  await expect(createAdapterForFixture(fixture).createSchema?.({}, 'auth-schema.sql')).rejects.toThrow(
    /can only generate definitions\.sql[\s\S]*auth-schema\.sql/,
  );
});

test('createSchema rejects nonempty definitions without a Better Auth fence', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': 'create table "posts" ("id" integer primary key not null);\n',
    },
  });

  await expect(createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql')).rejects.toThrow(
    /no sqlfu Better Auth managed section[\s\S]*-- sqlfu:better-auth begin/,
  );
});

test('createSchema rejects malformed Better Auth fences', async () => {
  const cases = [
    {
      name: 'dangling begin',
      definitionsSql: dedent`
        create table "posts" ("id" integer primary key not null);

        -- sqlfu:better-auth begin
        create table "user" ("id" text primary key not null);
      `,
      message: /exactly one sqlfu Better Auth managed section/,
    },
    {
      name: 'multiple sections',
      definitionsSql: dedent`
        -- sqlfu:better-auth begin
        create table "user" ("id" text primary key not null);
        -- sqlfu:better-auth end
        -- sqlfu:better-auth begin
        create table "session" ("id" text primary key not null);
        -- sqlfu:better-auth end
      `,
      message: /exactly one sqlfu Better Auth managed section/,
    },
    {
      name: 'end before begin',
      definitionsSql: dedent`
        -- sqlfu:better-auth end
        create table "posts" ("id" integer primary key not null);
        -- sqlfu:better-auth begin
      `,
      message: /malformed sqlfu Better Auth managed section/,
    },
  ];

  for (const testCase of cases) {
    await using fixture = await createBetterAuthFixture({
      files: {
        'definitions.sql': testCase.definitionsSql,
      },
    });

    await expect(
      createAdapterForFixture(fixture).createSchema?.({}, 'definitions.sql'),
      testCase.name,
    ).rejects.toThrow(testCase.message);
  }
});

test('createSchema uses integer foreign keys when Better Auth is configured for serial ids', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });

  const schema = await createAdapterForFixture(fixture).createSchema?.(
    {
      advanced: {
        database: {
          generateId: 'serial',
        },
      },
    } as any,
    'definitions.sql',
  );

  expect(schema?.code).toContain('"id" integer primary key not null');
  expect(schema?.code).toContain('"userId" integer not null references "user" ("id") on delete cascade');
});

test('createSchema follows the wrapped adapter table naming config', async () => {
  await using fixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });
  const adapter = sqlfuBetterAuthAdapter({
    sqlfu: {definitions: './definitions.sql', queries: './sql'},
    projectRoot: fixture.root,
    adapter: () =>
      createBaseAdapter({
        options: {
          adapterConfig: {
            adapterId: 'kysely',
            adapterName: 'Kysely Adapter',
            usePlural: true,
          },
        },
      }),
  })({});

  const schema = await adapter.createSchema?.({}, 'definitions.sql');

  expect(schema?.code).toContain('create table "users"');
  expect(schema?.code).toContain('create table "sessions"');
  expect(schema?.code).toContain('"userId" text not null references "users" ("id") on delete cascade');
});

test('generated Better Auth definitions can feed sqlfu draft and migrate', async () => {
  await using authFixture = await createBetterAuthFixture({
    files: {
      'definitions.sql': '',
    },
  });
  const schema = await createAdapterForFixture(authFixture).createSchema?.({}, 'definitions.sql');
  await using sqlfuFixture = await createMigrationsFixture('better-auth-adapter-sqlfu-workflow', {
    desiredSchema: dedent`
      create table "posts" ("id" integer primary key not null);

      ${schema!.code}
    `,
  });

  await sqlfuFixture.api.draft({name: 'better auth schema'});
  await sqlfuFixture.api.migrate();

  expect(await sqlfuFixture.listMigrationFiles()).toEqual([
    'migrations/2026-04-10T00.00.00.000Z_better_auth_schema.sql',
  ]);
  expect(await extractSchema(sqlfuFixture.db, 'main', {excludedTables: ['sqlfu_migrations']})).toContain(
    'create table user',
  );
});

test('createBetterAuthFixture runs auth generate and can reconfigure auth.ts', async () => {
  await using fixture = await createBetterAuthFixture(() => {
    return fixtureBetterAuth({
      database: fixtureSqlfuBetterAuthAdapter({
        sqlfu: fixtureSqlfuConfig,
        adapter: () => fixtureCreateBaseAdapter(),
      }),
      user: {
        additionalFields: {
          role: {
            type: 'string',
            required: false,
            fieldName: 'role',
          },
        },
      },
    });
  });

  await fixture.exec('auth generate --output definitions.sql --yes');

  const firstDefinitionsSql = await fixture.readText('definitions.sql');
  expect(firstDefinitionsSql).toContain('"role" text');

  await fixture.reconfigure(() => {
    return fixtureBetterAuth({
      database: fixtureSqlfuBetterAuthAdapter({
        sqlfu: fixtureSqlfuConfig,
        adapter: () => fixtureCreateBaseAdapter(),
      }),
      user: {
        additionalFields: {
          handle: {
            type: 'string',
            required: true,
            unique: true,
            fieldName: 'handle',
          },
        },
      },
    });
  });

  await fixture.exec('auth generate --output definitions.sql --yes');

  const secondDefinitionsSql = await fixture.readText('definitions.sql');
  expect(secondDefinitionsSql).not.toContain('"role" text');
  expect(secondDefinitionsSql).toContain('"handle" text not null unique');
});

async function createBetterAuthFixture(input: BetterAuthFixtureInput) {
  const root = await createTempFixtureRoot('better-auth-adapter');
  const files = typeof input === 'function' ? {'definitions.sql': '', 'sql/.gitkeep': ''} : input.files;
  await writeFixtureFiles(root, {
    'package.json': '{"type":"module"}\n',
    ...files,
  });

  await linkFixtureDependencies(root);

  if (typeof input === 'function') {
    await writeAuthConfig(root, input);
  }

  return {
    root,
    async exec(command: string) {
      return execaCommand(command, {
        cwd: root,
        env: {
          PATH: `${path.join(packageRoot, 'node_modules/.bin')}:${process.env.PATH}`,
          BETTER_AUTH_TELEMETRY_DISABLED: '1',
        },
      });
    },
    async reconfigure(fn: BetterAuthFixtureFactory) {
      await writeAuthConfig(root, fn);
    },
    async readText(relativePath: string) {
      return fs.readFile(path.join(root, relativePath), 'utf8');
    },
    async writeText(relativePath: string, contents: string) {
      await fs.writeFile(path.join(root, relativePath), contents);
    },
    async [Symbol.asyncDispose]() {
      await fs.rm(root, {recursive: true, force: true});
    },
  };
}

type BetterAuthFixtureFactory = () => unknown;
type BetterAuthFixtureInput = BetterAuthFixtureFactory | {files: Record<string, string>};

async function linkFixtureDependencies(root: string) {
  const nodeModules = path.join(root, 'node_modules');
  await fs.mkdir(nodeModules, {recursive: true});
  await fs.symlink(packageRoot, path.join(nodeModules, 'sqlfu'), 'dir');
  await fs.symlink(path.join(packageRoot, 'node_modules/better-auth'), path.join(nodeModules, 'better-auth'), 'dir');
}

async function writeAuthConfig(root: string, fn: BetterAuthFixtureFactory) {
  await fs.writeFile(
    path.join(root, 'auth.ts'),
    dedent`
      import {betterAuth} from 'better-auth';
      import {sqlfuBetterAuthAdapter} from 'sqlfu/better-auth';

      const sqlfuConfig = {
        definitions: './definitions.sql',
        queries: './sql',
      };
      const fixtureBetterAuth = betterAuth;
      const fixtureSqlfuBetterAuthAdapter = sqlfuBetterAuthAdapter;
      const fixtureSqlfuConfig = sqlfuConfig;

      const createBaseAdapter = () => {
        const baseAdapter = {
          id: 'kysely',
          async create() {
            return {};
          },
          async findOne() {
            return null;
          },
          async findMany() {
            return [];
          },
          async count() {
            return 0;
          },
          async update() {
            return null;
          },
          async updateMany() {
            return 0;
          },
          async delete() {},
          async deleteMany() {
            return 0;
          },
          async transaction(callback) {
            return callback(baseAdapter);
          },
          options: {
            adapterConfig: {
              adapterId: 'kysely',
              adapterName: 'Kysely Adapter',
              supportsBooleans: false,
            },
          },
        };

        return baseAdapter;
      };
      const fixtureCreateBaseAdapter = createBaseAdapter;

      const getAuth = ${fn.toString()};

      export const auth = getAuth();
    `,
  );
}

function createAdapterForFixture(fixture: Awaited<ReturnType<typeof createBetterAuthFixture>>) {
  return sqlfuBetterAuthAdapter({
    sqlfu: {definitions: './definitions.sql', queries: './sql'},
    projectRoot: fixture.root,
    adapter: () => createBaseAdapter(),
  })({});
}

function createBaseAdapter(overrides: Record<string, unknown> = {}) {
  const baseAdapter = {
    id: 'kysely',
    async create() {
      return {};
    },
    async findOne() {
      return null;
    },
    async findMany() {
      return [];
    },
    async count() {
      return 0;
    },
    async update() {
      return null;
    },
    async updateMany() {
      return 0;
    },
    async delete() {},
    async deleteMany() {
      return 0;
    },
    async transaction(callback: (adapter: unknown) => Promise<unknown>) {
      return callback(baseAdapter);
    },
    options: {
      adapterConfig: {
        adapterId: 'kysely',
        adapterName: 'Kysely Adapter',
        supportsBooleans: false,
      },
    },
    ...overrides,
  };

  return baseAdapter as any;
}
